timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5
url: "https://github.com/sudokhan112/Model-thinking/edit/gh-pages/index.md"
theme: jekyll-theme-cayman
